# Generated by Django 2.2 on 2019-04-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('full_name', models.CharField(max_length=254)),
                ('age', models.CharField(max_length=2)),
                ('child_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('allergy', models.TextField(max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'children',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check in')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check out')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=254)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Classroom'),
        ),
        migrations.AddField(
            model_name='child',
            name='guardians',
            field=models.ManyToManyField(related_name='children', to='core.Guardian'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output'), ('NP', 'Nap')], max_length=2)),
                ('subtype', models.CharField(max_length=50, null=True)),
                ('subtype_option', models.CharField(max_length=50, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(default=False, verbose_name='End time')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.Child')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.Visit')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
