# Generated by Django 2.2 on 2019-04-16 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('full_name', models.CharField(max_length=254)),
                ('age', models.CharField(max_length=2)),
                ('child_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_pic', models.ImageField(null=True, upload_to='')),
                ('allergy', models.TextField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Last name, First name', max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check in')),
                ('check_out', models.DateTimeField(default=False, verbose_name='Check out')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=254)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Classroom'),
        ),
        migrations.AddField(
            model_name='child',
            name='guardians',
            field=models.ManyToManyField(related_name='children', to='core.Guardian'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('FD', 'Food'), ('NS', 'Nurse'), ('BT', 'Bottle'), ('NP', 'Nap'), ('DP1', 'Diaper1'), ('DP2', 'Diaper2')], max_length=2)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(default=False, verbose_name='End time')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.Child')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.Visit')),
            ],
        ),
    ]
