# Generated by Django 2.2 on 2019-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'children'},
        ),
        migrations.AlterField(
            model_name='child',
            name='child_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
