# Generated by Django 2.2 on 2019-04-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190417_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='subtype_option',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output'), ('NP', 'Nap')], max_length=2),
        ),
    ]
