# Generated by Django 2.2 on 2019-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190419_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, default=True, null=True, verbose_name='End time'),
        ),
    ]
