# Generated by Django 2.2 on 2019-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190418_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='check_out',
        ),
        migrations.AlterField(
            model_name='visit',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
