# Generated by Django 2.2 on 2019-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190418_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check out'),
        ),
    ]
